# Rio Term Configuration - Kunal Kumar
draw-bold-text-with-light-colors = true
hide-mouse-cursor-when-typing = false
theme = "Floraverse"
line-height = 1.2
working-dir = "$HOME"
confirm-before-quit = false
use-kitty-keyboard-protocol = true

[cursor]
shape = 'block'
blinking = true
blinking-interval = 800

[editor]
program = "vim"

[window]
mode = "maximized"
opacity = 1.0
blur = true
decorations = "disabled"
colorspace = "display-p3"

[renderer]
performance = "low"
backend = "automatic"
disable-unfocused-render = false
level = 1
disable-occluded-render = true
target-fps = 60

[keyboard]
disable-ctlseqs-alt = true
ime-cursor-positioning = true

[fonts]
size = 18
family = "DepartureMono Nerd Font"
style = "Normal"
width = "Medium"
use-drawable-chars = true
hinting = true

[fonts.emoji]
family = "Noto Color Emoji"

[shell]
program = "zsh"
